//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackgroundDesktopApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrackTime
    {
        public int UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Note { get; set; }
        public string Duration { get; set; }
        public string MatterIDPodio { get; set; }
        public string MatterIDColio { get; set; }
        public string MatterIDSlack { get; set; }
        public string MatterName { get; set; }
        public int Id { get; set; }
    }
}
